events {}

http {
    include mime.types;

    server {
        listen 8081;
        root /usr/share/nginx/html/blue;
        index index.html;
    }

    server {
        listen 8082;
        root /usr/share/nginx/html/green;
        index index.html;
    }

    server {
        listen 8083;
        root /usr/share/nginx/html/red;
        index index.html;
    }
}